#!/usr/bin/env bash
# Copyright 2014-2022 GSI, Inc. All rights reserved.
#
#

TOOL_NAME="$(basename $0)"

#=============================================================================
# ***** OPTARG *****
#=============================================================================
DDS_SESSION_ID=""
SUBMISSION_ID=""
while getopts "a:s:" opt; do
  case "$opt" in
  a) DDS_SESSION_ID="$OPTARG"
    ;;
  s)
    SUBMISSION_ID="$OPTARG"
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  esac
done

eval WORK_DIR=$(dds-user-defaults --session $DDS_SESSION_ID --key server.work_dir)
eval WRK_PKG=$(dds-user-defaults --session $DDS_SESSION_ID --wrkpkg --submission-id $SUBMISSION_ID)
eval RMS_SANDBOX=$(dirname $WRK_PKG)
eval WRK_S_L=$(dds-user-defaults --session $DDS_SESSION_ID --wrkscript --submission-id $SUBMISSION_ID)

#=============================================================================
# ***** DDS NAMED PIPE *****
#=============================================================================
# a dds-slurm communication pipe (log engine)
eval pipe_dir="$WORK_DIR"
pipe="$pipe_dir/$SUBMISSION_ID/.dds_slurm_pipe"
if [[ ! -p $pipe ]]; then
    echo "$TOOL_NAME error: dds-slurm log engine is not running"
    exit 1
fi
#=============================================================================
# ***** LOG *****
#=============================================================================
# function read input from stdin and write output to the stdout
# caller must take care about where come stdin and where go stdout
logMsgPipe() 
{
  while read data
  do
      logMsg "$data" 
  done
}
logMsg()
{
	echo -e "$TOOL_NAME: $1" > $pipe
}

#=============================================================================
# ***** MAIN *****
#=============================================================================
logMsg "Submitting DDS Job on the SLURM cluster..."
# Set execute access for job.slurm
chmod +x $RMS_SANDBOX/job.slurm
JOB_ID=$(sbatch --parsable $RMS_SANDBOX/job.slurm)
if (( $? != 0 )) ; then
	logMsg "Error: Failed to submit SLURM job ($?)"
	exit $?
fi
logMsg "SLURM: $JOB_ID"
echo $JOB_ID > "$WORK_DIR/$SUBMISSION_ID/.dds_slurm_jobid"

exit 0
